function settings(window, data, callback)
%SETTINGS Summary of this function coming soon..
%   Detailed explanation coming soon..
%
%	Copyright © 2014 Alexander Isakov. Contact: <alexander.isakov@tuhh.de>
%	Copyright © 2014 Marina Krotofil. Contact: <marina.krotofil@tuhh.de>
%	Copyright © 2014 TUHH-SVA Security in Distributed Applications.
%	All rights reserved.
%	License: http://opensource.org/licenses/BSD-3-Clause
%	----------------------------------------------------------------------

    set(window, 'Name', 'Settings');
    set(window, 'NumberTitle', 'off');
    set(window, 'MenuBar', 'none');
    set(window, 'Toolbar', 'none');
    set(window, 'Position', [0,0,300,400]);
    center(window);
    interface.window = window;

    grid = uiextras.Grid('Parent', window, ...
        'Spacing', 6, ...
        'Padding', 4);
    tabs = uiextras.TabPanel('Parent', grid);
    % simulation
    panel = uipanel('Parent', tabs);
    vbox = uiextras.VBox('Parent', panel, ...
        'Spacing', 4, ...
        'Padding', 10);
    uicontrol('Parent', vbox, ...
              'Style', 'text', ...
              'FontSize', 11, ...
              'HorizontalAlignment', 'left', ...
              'String', 'Duration');
    hbox = uiextras.HBox('Parent', vbox, ...
                'Spacing', 4);
    interface.simulation.duration = uicontrol('Parent', hbox, ...
            'Style', 'edit', ...
            'HorizontalAlignment', 'left', ...
            'FontSize', 11, ...
            'String',  data.simulation.duration);
    interface.simulation.durationunits = uicontrol('Parent', hbox, ...
                'Style', 'popup', ...
                'FontSize', 8, ...
                'String', TimeUnits.Units(), ...
                'Value', 1);
	set(hbox, 'Sizes', [-1 80]);
    set(vbox, 'Sizes', [18 20]);
    % disturbances
    panel = uipanel('Parent', tabs);
    vbox = uiextras.VBox('Parent', panel, ...
        'Spacing', 4, ...
        'Padding', 10);
    % first
    disturbances(1) = uicontrol('Parent', vbox, ...
              'Style', 'checkbox', ...
              'String', 'First', ...
              'Value', data.simulation.disturbances(1));
    disturbances(2) = uicontrol('Parent', vbox, ...
      'Style', 'checkbox', ...
      'String', 'Second', ...
      'Value', data.simulation.disturbances(2));
    disturbances(3) = uicontrol('Parent', vbox, ...
      'Style', 'checkbox', ...
      'String', 'Third', ...
      'Value', data.simulation.disturbances(3));
    disturbances(4) = uicontrol('Parent', vbox, ...
      'Style', 'checkbox', ...
      'String', 'Fourth', ...
      'Value', data.simulation.disturbances(4));
    disturbances(5) = uicontrol('Parent', vbox, ...
      'Style', 'checkbox', ...
      'String', 'Fifth', ...
      'Value', data.simulation.disturbances(5));
    disturbances(6) = uicontrol('Parent', vbox, ...
        'Style', 'checkbox', ...
        'String', 'Sixth', ...
        'Value', data.simulation.disturbances(6));
    disturbances(7) = uicontrol('Parent', vbox, ...
      'Style', 'checkbox', ...
      'String', 'Seventh', ...
      'Value', data.simulation.disturbances(7));
    interface.simulation.disturbances = disturbances;
    set(vbox, 'Sizes', ones(1, 7)*20);
    % callbacks
    panel = uipanel('Parent', tabs);
    vbox = uiextras.VBox('Parent', panel, ...
        'Spacing', 4, ...
        'Padding', 10);
    uicontrol('Parent', vbox, ...
              'Style', 'text', ...
              'FontSize', 9, ...
              'HorizontalAlignment', 'left', ...
              'String', 'After end:');
    interface.simulation.callbacks.afterend = uicontrol('Parent', vbox, ...
            'Style', 'edit', ...
            'HorizontalAlignment', 'left', ...
            'FontSize', 11, ...
            'Max', 5, ...
            'Min', 0, ...
            'String',  data.simulation.callbacks.afterend);
    set(vbox, 'Sizes', [18 -1]);
    tabs.TabNames = {'General', 'Disturbances', 'Callbacks'};
    tabs.SelectedChild = 1;
    %buttons
    buttons = uiextras.HButtonBox('Parent', grid, ...
            'HorizontalAlignment', 'right', ...
            'Padding', 10);
    interface.buttons.apply = uicontrol('Parent', buttons, ...
        'String', 'Apply', ...
        'Callback', @onApply);
    function onApply(~,~)
        %simulation/duration
        value = str2double(get(interface.simulation.duration, 'String'));
        if isempty(value)
            warning('VAC:settings:onApply', 'Value must be a number.');
            set(interface.simulation.duration, 'String', 24);
            return;
        end
        if value <= 0
            warning('VAC:settings:onApply', 'Value must be a positiv double.');
            set(interface.simulation.duration, 'String', 24);
            return;
        end
        switch get(interface.simulation.durationunits, 'Value')
            case TimeUnits.MINUTES.Value
                options.simulation.duration = value/60;
            case TimeUnits.SECONDS.Value
                options.simulation.duration = value/3600;
            otherwise
                options.simulation.duration = value;
        end
        %disturbances
        for i = 1:length(interface.simulation.disturbances)
           options.simulation.disturbances(i) = get(interface.simulation.disturbances(i), 'Value');
        end
        %callbacks
        options.simulation.callbacks.afterend = get(interface.simulation.callbacks.afterend, 'String');
        %call back
        callback(options);
        close(interface.window);
    end % onApply
    interface.buttons.apply = uicontrol('Parent', buttons, ...
        'String', 'Cancel', ...
        'Callback', @onCancel);
    function onCancel(~,~)
        close(interface.window);
    end % onApply
    set(grid, 'RowSizes', [-1 45]);
end

