%-g -DDEBUG
mex         ccode/vamex.c ... 
            ccode/prototypes.c ...
            ccode/VAModelb.c ...
            ccode/vaporizer.c ...
            ccode/reactor.c ...
            ccode/reaction_rate.c ...
            ccode/Cp.c ...
            ccode/separator.c ...
            ccode/beta_separator.c ...
            ccode/absorber.c ...
            ccode/column.c ...
            ccode/bubpt_column.c ...
            ccode/enthalpy_3.c ...
            ccode/Ludcmp.c ...
            ccode/gamma_wilson_3.c ...
            ccode/mixer.c ...
            ccode/enthalpy_7.c ...
            ccode/gamma_wilson_7.c ...
            ccode/steadystate.c ...
            ccode/Gas_Remove.c ...
            ccode/Compressor.c ...
            ccode/CO2_Remove.c ...
            ccode/FEHE.c ...
            ccode/ComponentSeparator.c

% mex -DDEBUG -g ccode/vamex.c ...
%             ccode/VAModelb.c ...
%             ccode/vaporizer.c ...
%             ccode/reactor.c ...
%             ccode/reaction_rate.c ...
%             ccode/Cp.c ...
%             ccode/separator.c ...
%             ccode/beta_separator.c ...
%             ccode/absorber.c ...
%             ccode/column.c ...
%             ccode/bubpt_column.c ...
%             ccode/enthalpy_3.c ...
%             ccode/Ludcmp.c ...
%             ccode/gamma_wilson_3.c ...
%             ccode/mixer.c ...
%             ccode/enthalpy_7.c ...
%             ccode/gamma_wilson_7.c ...
%             ccode/steadystate.c ...
%             ccode/Gas_Remove.c ...
%             ccode/Compressor.c ...
%             ccode/CO2_Remove.c ...
%             ccode/FEHE.c ...
%             ccode/ComponentSeparator.c